% This script plots the wind and wave rose together as subplots on a larger
% figure. The wind rose is colored by wind speed and the wave rose is
% colored by Hs
%
% Figure 3: Wind (left) and wave (right) data for Bogue Banks from
% 2008-2016. Measured from NDBC wind gage CLKN7, Waverider buoy 4110, and
% NOAA tide gage 8656483
%
% Michael Itzkin, 4/5/2018
%-----------------------------------------------------------------------%
close all
clear all
clc

% Load the data
data = csvread('../Data/Bogue Data 2008-2016.csv');
Hs = data(:,1);
Tide = data(:,2);
Times = data(:,3);
Tp = data(:,4);
waveDirs = data(:,5);
windDirs = data(:,6);
speed = data(:,7);

% Make the figure
makeFigure(windDirs, speed, waveDirs, Hs);

% Make a .txt file summarizing the environmental data
makeTxtFile(Times, Tide, Hs, windDirs, speed)


function makeFigure(windDirs, speed, waveDirs, Hs)
    % Make the figure

    Title = 'Figure 3';
    Figure = figure('Name', Title);

    % The left subplot will be the wind rose
    subplot(1,2,1)
    makeWindRose(windDirs, speed)

    % The right subplot will be the wave rose
    subplot(1,2,2)
    makeWaveRose(waveDirs, Hs)

    % Save the figure
    saveName = sprintf('..%sFigures%s%s.png', filesep, filesep, Title);
    print(saveName, '-dpng')
    close()
    
end

function makeTxtFile(Times, Tide, Hs, windDirs, speed)
    % Make a .txt file summarizing the environmental data
    
    % Identify the beginning and end date and print
    beginning = datetime(Times(1), 'ConvertFrom', 'datenum');
    finish = datetime(Times(end), 'ConvertFrom', 'datenum');

    % Create the .txt file
    fname = sprintf('..%sText Files%sBogue Banks Environmental Data Overview (%s to %s).txt',...
        filesep, filesep, beginning, finish);
    fid = fopen(fname, 'w');
    if fid == -1
        fprintf('ERROR! Could not open file!')
    else

        fprintf(fid, 'Bogue Banks data from %s to %s:\n\n',...
            beginning,...
            finish);

        % Print out the tidal range and mean Hs range
        fprintf(fid, 'Tidal Range (m) = %.4f (%.2fm to %.2fm)\n',...
            nanmax(Tide)-nanmin(Tide),...
            nanmin(Tide),...
            nanmax(Tide));
        fprintf(fid, 'Hs Range (m) = %.2f±%.2f (%.2fm to %.2fm)\tMedian: %0.2f\n\n',...
            nanmean(Hs),...
            2*nanstd(Hs),...
            nanmin(Hs),...
            nanmax(Hs),...
            nanmedian(Hs));

        % Print out the mean wind direction and speed
        fprintf(fid, 'Mean wind direction (deg) = %.2f\n',...
            nanmean(windDirs));
        fprintf(fid, 'Mean wind speed (m/s) = %.2f±%.2f\tMedian: %0.2f\tRange: %0.2f (%0.4f - %0.4f)\n\n',...
            nanmean(speed),...
            2*nanstd(speed),...
            nanmedian(speed),...
            nanmax(speed) - nanmin(speed),...
            nanmin(speed),...
            nanmax(speed));

        % Print out the greatest Hs and WindSpeed
        fprintf(fid, 'Strongest winds (m/s) = %.2f\n',...
            nanmax(speed));
        fprintf(fid, 'Largest Hs (m) = %.2f\n\n',...
            nanmax(Hs));

        % See what day the strongest Hs occured
        day_1 = find(Hs == nanmax(Hs));
        fprintf(fid, 'Largest Hs occurred on %s: %.2fm (%.2fm/s winds)\n',...
            datetime(Times(day_1), 'ConvertFrom', 'datenum'),...
            Hs(day_1),...
            speed(day_1));

        % See what day the strongest winds occured
        day_2 = find(speed == nanmax(speed));
        fprintf(fid, 'Largest wind speeds occurred on %s: %.2fm/s (%.2fm Hs)\n',...
            datetime(Times(day_2), 'ConvertFrom', 'datenum'),...
            speed(day_2),...
            Hs(day_2));

    end

    f_end = fclose(fid);
    if f_end == -1
        fprintf('ERROR! Could not close file!\n')
    else
        fprintf('File saved successfully\n')
        pause(2)
    end

    close all
    clc
end

function makeWindRose(dirs, speed)
    % Make a wind rose colored by wind speed
    
    % Convert the wind directions to radians
    dirs = deg2rad(dirs);

    % Set how many bins to sort the data into 
    numBins = 36;  % 36 = 10° bins

    % Make 5m/s sized categories for the wind speeds and set a vector of the
    % speed categories
    speedBinSize = 5;
    [Y, ~] = discretize(speed, min(speed):speedBinSize:max(speed));
    speedCats = min(Y):1:max(Y);

    % Make the figure colored by wind speed
    Title = 'Wind';

    cols = jet(length(speedCats));

    a = polarhistogram(dirs(Y == 6), numBins,...
        'FaceColor', cols(6,:),...
        'EdgeColor', 'black',...
        'FaceAlpha', 0.5,...
        'DisplayName', '30-35');
    hold on
    b = polarhistogram(dirs(Y == 5), numBins,...
        'FaceColor', cols(5,:),...
        'EdgeColor', 'black',...
        'FaceAlpha', 0.5,...
        'DisplayName', '25-30');
    c = polarhistogram(dirs(Y == 4), numBins,...
        'FaceColor', cols(4,:),...
        'EdgeColor', 'black',...
        'FaceAlpha', 0.5,...
        'DisplayName', '15-20');
    d =polarhistogram(dirs(Y == 3), numBins,...
        'FaceColor', cols(3,:),...
        'EdgeColor', 'black',...
        'FaceAlpha', 0.5,...
        'DisplayName', '10-15');
    e = polarhistogram(dirs(Y == 2), numBins,...
        'FaceColor', cols(2,:),...
        'EdgeColor', 'black',...
        'FaceAlpha', 0.5,...
        'DisplayName', '5-10');
    f = polarhistogram(dirs(Y == 1), numBins,...
        'FaceColor', cols(1,:),...
        'EdgeColor', 'black',...
        'FaceAlpha', 0.5,...
        'DisplayName', '0-5');

    lgd = legend([f,e,d,c,b,a],...
        'Location', 'Northeastoutside');
    title(lgd, 'Wind Speed (m/s)')
    title(Title,...
        'FontSize', 14,...
        'FontWeight', 'bold')
end

function makeWaveRose(dirs, Hs)
    % Make a wave rose colored by Hs

    % Convert the wind directions to radians
    dirs = deg2rad(dirs);

    % Set how many bins to sort the data into 
    numBins = 36;  % 36 = 10° bins

    % Make 1m/s sized categories for the wind speeds and set a vector of the
    % speed categories
    hsBinSize = 1;
    [Y, ~] = discretize(Hs, floor(min(Hs)):hsBinSize:ceil(max(Hs)));
    hsCats = min(Y):1:max(Y);

    % Make the figure colored by wind speed
    Title = 'Wave';

    cols = jet(length(hsCats));


    a = polarhistogram(dirs(Y == 5), numBins,...
        'FaceColor', cols(5,:),...
        'EdgeColor', 'black',...
        'FaceAlpha', 0.5,...
        'DisplayName', '4-5');
    hold on
    b = polarhistogram(dirs(Y == 4), numBins,...
        'FaceColor', cols(4,:),...
        'EdgeColor', 'black',...
        'FaceAlpha', 0.5,...
        'DisplayName', '3-4');
    c =polarhistogram(dirs(Y == 3), numBins,...
        'FaceColor', cols(3,:),...
        'EdgeColor', 'black',...
        'FaceAlpha', 0.5,...
        'DisplayName', '2-3');
    d = polarhistogram(dirs(Y == 2), numBins,...
        'FaceColor', cols(2,:),...
        'EdgeColor', 'black',...
        'FaceAlpha', 0.5,...
        'DisplayName', '1-2');
    e = polarhistogram(dirs(Y == 1), numBins,...
        'FaceColor', cols(1,:),...
        'EdgeColor', 'black',...
        'FaceAlpha', 0.5,...
        'DisplayName', '0-1');

    lgd = legend([e,d,c,b,a],...
        'Location', 'Northeastoutside');
    title(lgd, 'Hs (m)')
    title(Title,...
        'FontSize', 14,...
        'FontWeight', 'bold')

end